export const surpriseMePrompts = [
  'a tiny astronaut drinking coffee on top of a giant mushroom, cinematic digital art',
  'a cozy treehouse library hidden inside an ancient forest, warm sunlight, fantasy art',
  'a golden retriever wearing a detective coat investigating a mysterious suitcase, cinematic photography',
  'a futuristic city built vertically inside a massive canyon, flying vehicles, concept art',
  'a majestic lion wearing an elaborate Victorian suit, dramatic studio portrait',
  'a small robot gardener watering glowing flowers on an alien planet, 3D render',
  'an underwater library filled with ancient books and floating jellyfish, surreal digital art',
  'a Japanese ramen shop on the Moon, Earth visible through the window, cinematic illustration',
  'a vintage Volkswagen van driving through a desert filled with giant cacti at sunset, 35mm photography',
  'a wizard running a tiny coffee shop for magical creatures, cozy fantasy illustration',
  'a polar bear sitting in a neon-lit cyberpunk arcade, cinematic photography',
  'a futuristic greenhouse floating above the clouds, lush tropical plants, concept art',
  'a medieval knight riding a giant snail through an enchanted forest, whimsical digital art',
  'a glass cabin surrounded by snowy mountains under the northern lights, architectural photography',
  'a sleepy orange cat curled up inside an astronaut helmet on a spaceship, soft cinematic lighting',
  'a colossal whale swimming through the clouds above a futuristic city, surreal digital art',
  'a Victorian-era train traveling across a giant suspension bridge above the ocean, cinematic photography',
  'a magical bookstore where the books are floating in the air, warm candlelight, fantasy art',
  'a fox wearing a space suit exploring the surface of Mars, realistic photography',
  'a futuristic African city at night with glowing skyscrapers and autonomous flying taxis, concept art',
  'a giant teacup house sitting in the middle of a flower field, whimsical 3D render',
  'a samurai standing beneath a waterfall during a thunderstorm, dramatic cinematic composition',
  'a futuristic motorcycle racing through a neon city at midnight, motion blur, 50mm photography',
  'a penguin running a sophisticated five-star restaurant in Antarctica, humorous digital art',
  'an ancient castle floating above a sea of clouds at sunrise, epic fantasy concept art',
  'a miniature city inside a glass bottle sitting on an old wooden desk, magical realism',
  'a beautiful underwater coral palace illuminated by bioluminescent creatures, fantasy art',
  'a retro 1980s computer transforming into a futuristic holographic workstation, synthwave style',
  'a group of raccoons having a formal business meeting inside a modern office, cinematic photography',
  'a peaceful village built inside the branches of an enormous ancient tree, fantasy illustration',
  'a chrome robot playing electric guitar on stage in a futuristic concert hall, neon lighting',
  'a mysterious lighthouse standing on a floating island above a stormy ocean, cinematic digital art',
  'a professional food photograph of a glowing blue dessert shaped like a small planet',
  'a futuristic space station designed like a giant tropical resort, colorful concept art',
  'a black cat sitting on a rooftop overlooking a rainy cyberpunk city, neon reflections',
  'a giant mechanical elephant walking through the streets of a futuristic city, cinematic photography',
  'a cozy cabin inside a giant hollow tree during autumn, warm interior lighting, fantasy art',
  'a medieval dragon working as a blacksmith in a small village workshop, detailed digital painting',
  'a surreal desert where enormous clocks grow from the sand like flowers, dreamlike artwork',
  'a futuristic submarine exploring the ruins of an ancient underwater civilization, cinematic concept art',
  'a corgi dressed as a medieval king sitting on an ornate throne, dramatic royal portrait',
  'a beautiful futuristic train traveling through a glowing tunnel beneath the ocean, cinematic photography',
  'a giant moon hovering extremely close above a peaceful mountain village, realistic landscape photography',
  'a scientist discovering a tiny glowing galaxy inside a laboratory glass jar, surreal digital art',
  'a futuristic rooftop garden above a dense megacity during sunset, architectural photography',
  'a pirate ship sailing through outer space surrounded by colorful nebulae, epic fantasy illustration',
  'a robot sitting alone on a park bench watching the sunset, emotional cinematic photography',
  'a massive ancient temple hidden inside a jungle covered with glowing blue plants, adventure concept art',
  'a futuristic African marketplace filled with colorful holographic signs, nighttime photography',
  'a small café on top of a skyscraper overlooking a massive futuristic city, cozy cinematic atmosphere',
  'a giant butterfly made of stained glass flying through an enchanted forest, magical fantasy art',
];